import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Routing & Rendering Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex ... border-solid border-2 border-indigo-600">
          <Link className="flex-1 h-16 ..." href="/">
            home
          </Link>
          <Link className="flex-1 h-16 ..." href="/rendering/ssg">
            SSG
          </Link>
          <Link className="flex-1 h-16 ... " href="/rendering/isr">
            ISR
          </Link>
          <Link className="flex-1 h-16 ..." href="/rendering/ssr">
            SSR
          </Link>
          <Link className="flex-1 h-16 ..." href="/rendering/csr">
            CSR
          </Link>
        </nav>
        <div className="inline-block align-middle">{children}</div>
      </body>
    </html>
  );
}
